TRELLO_BOARDS_FIXTURE = [
    {
        'closed': False,
        'creationMethod': None,
        'dateLastActivity': '2019-02-12T13:34:00.614Z',
        'dateLastView': '2019-02-05T18:25:43.064Z',
        'desc': 'Test Board Desc',
        'id': '123',
        'name': 'Test Board Name',
        'pinned': True,
        'powerUps': [],
        'url': 'https://trello.com/b/001',
    },
    {
        'closed': False,
        'creationMethod': None,
        'dateLastActivity': '2019-02-12T13:34:00.614Z',
        'dateLastView': '2019-02-05T18:43:49.064Z',
        'desc': 'Test Board Desc',
        'id': '123',
        'name': 'Test Board Name',
        'pinned': True,
        'powerUps': [],
        'url': 'https://trello.com/b/002',
    },
]
TRELLO_COLUMNS_FIXTURE = [
    {
        'closed': False,
        'id': 'abc-1',
        'idBoard': '123',
        'name': 'Col Name',
        'pos': 1,
        'softLimit': None,
        'subscribed': False,
    },
    {
        'closed': False,
        'id': 'abc-2',
        'idBoard': '123',
        'name': 'Col Name',
        'pos': 2,
        'softLimit': None,
        'subscribed': False,
    },
    {
        'closed': False,
        'id': 'abc-3',
        'idBoard': '123',
        'name': 'Col Name',
        'pos': 3,
        'softLimit': None,
        'subscribed': False,
    },
]
